export const music = [
	"Johann Strauss - Donau Walzer (performed by European Archive; Used for all songs #1)",
	"Dead Combo - Povo Que Cas Descalo (Used for all songs #2)",
	"Convergence - Vanished Memories",
	"Frederic Chopin - Nocturnes",
	"Girlschool - Night Before",
	"Nirvana - Nevermind - 01 - Smells Like Teen Spirit",
	"Nirvana - Nevermind - 02 - In Bloom",
	"Nirvana - Nevermind - 03 - Come as you Are",
	"Nirvana - Nevermind - 04 - Breed",
	"Nirvana - Nevermind - 05 - Polly",
	"Nirvana - Nevermind - 06 - Territorial Pissings",
	"Nirvana - Nevermind - 07 - Drain you",
	"Nirvana - Nevermind - 08 - Lounge Act",
	"Nirvana - Nevermind - 09 - Stay Away",
	"Nirvana - Nevermind - 10 - On a Plain",
	"Nirvana - Nevermind - 11 - Something in the Way",
	"RainbowHorse - Underground Walrus",
	"Crucified Barbara - In The Red - 01 - I Sell My Kids For Rock'N'Roll",
	"Crucified Barbara - In The Red - 02 - To Kill A Man",
	"Crucified Barbara - In The Red - 03 - Electric Sky",
	"Crucified Barbara - In The Red - 04 - The Ghost Inside",
	"Crucified Barbara - In The Red - 05 - Don't Call On Me",
	"Crucified Barbara - In The Red - 06 - In The Red",
	"Crucified Barbara - In The Red - 06 - Lunatic #1",
	"Crucified Barbara - In The Red - 07 - Shadows",
	"Crucified Barbara - In The Red - 08 - Finders Keepers",
	"Crucified Barbara - In The Red - 09 - Do You Want Me",
	"Crucified Barbara - In The Red - 10 - Follow The Stream",
	"Fortadelis - Stimulus - 01 - Aftermath",
	"Fortadelis - Stimulus - 02 - Clustered",
	"Fortadelis - Stimulus - 03 - Stimulus",
	"Fortadelis - Stimulus - 04 - Digital Wastelands",
	"Fortadelis - Stimulus - 05 - Synthesia",
	"Diaries of a hero - Behind the mask - 01 - Shine upon the sun",
	"Diaries of a hero - Behind the mask - 02 - Behind the mask",
	"Diaries of a hero - Behind the mask - 03 - Broken tears",
	"Diaries of a hero - Behind the mask - 04 - Follow the hero",
	"Diaries of a hero - Behind the mask - 05 - Scars of addiction",
	"Diaries of a hero - Behind the mask - 06 - Southern belles",
	"Diaries of a hero - Behind the mask - 07 - Ashes in the rain",
	"Diaries of a hero - Behind the mask - 08 - Mirror house",
	"Diaries of a hero - Behind the mask - 09 - Emotions",
	"Diaries of a hero - Behind the mask - 10 - My own tragedy",
	"Die Toten Hosen - In aller Stille - 01 - Strom",
	"Die Toten Hosen - In aller Stille - 02 - Innen alles neu",
	"Die Toten Hosen - In aller Stille - 03 - Disco",
	"Die Toten Hosen - In aller Stille - 04 - Teil von mir",
	"Die Toten Hosen - In aller Stille - 05 - Auflösen",
	"Die Toten Hosen - In aller Stille - 06 - Leben ist tödlich",
	"Die Toten Hosen - In aller Stille - 07 - Ertrinken",
	"Die Toten Hosen - In aller Stille - 08 - Alles was war",
	"Die Toten Hosen - In aller Stille - 09 - Pessimist",
	"Die Toten Hosen - In aller Stille - 10 - Wir bleiben stumm",
	"Die Toten Hosen - In aller Stille - 11 - Die letzte Schlacht",
	"Die Toten Hosen - In aller Stille - 12 - Tauschen gegen dich",
	"Die Toten Hosen - In aller Stille - 13 - Angst",
]